services:
  - type: web
    name: FT2
    env: python3
    ootDir: paper_trading_system
    buildCommand: pip install -r requirements.txt
    startCommand: python3 forward_tester.py
    envVars:
      - key: EXCHANGE
        value: binance
      - key: SYMBOL
        value: ETH/USDT
      - key: TELEGRAM_ENABLED
        value: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: LOG_LEVEL
        value: INFO
